### ISSUE TITLE
topojson for ubuntu 14.04

### ISSUE THREAD

**Issue by josephzhao** [mbostock/topojson#207]
I installed topojson on ubuntu 14.04 with command

npm install -g topojson

and run topojson has error:

/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node: undefined symbol: _ZN2v811HandleScopeC1Ev
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at bindings (/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/topojson/node_modules/d3/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:349:32)
    at Function.Module._load (module.js:305:12)

what is my problem?

thanks

Joseph

**Comment by hugolpz** [comment]
To close.

**Comment by mbostock** [comment]
FWIW, I’m hoping to eliminate the JSDOM dependency in D3 so that the contextify hurdle is removed for all.
