### ISSUE TITLE
Error: Cannot find module 'rw'

### ISSUE THREAD

**Issue by bsullins** [mbostock/topojson#277]
I'm following @mbostock example [Let's Make A Bubble Map](https://bost.ocks.org/mike/bubble-map/l) and am receiving the error "Cannot find module 'rw'" when running the Makefile build/counties.json

I'm on Mac OSX El Capitan (10.11.4) with homebrew and node v0.12.7 installed. 

Here is my Makefile:
```Makefile
all: us.json

clean:
	rm -rf -- us.json build

.PHONY: all clean

build/gz_2010_us_050_00_20m.shp: build/gz_2010_us_050_00_20m.zip
	unzip -od $(dir $@) $<
	touch $@

build/gz_2010_us_050_00_20m.zip:
	mkdir -p $(dir $@)
	curl -o $@ http://www2.census.gov/geo/tiger/GENZ2010/gz_2010_us_050_00_20m.zip

build/counties.json: build/gz_2010_us_050_00_20m.shp
	node_modules/.bin/topojson \
		-o build/counties.json \
		--projection='width = 960, height = 600, d3.geo.albersUsa() \
			.scale(1280) \
			.translate([width / 2, height / 2])' \
		--simplify=.5 \
		-- counties=build/gz_2010_us_050_00_20m.shp

build/states.json: build/counties.json
	node_modules/.bin/topojson-merge \
		-o $@ \
		--in-object=counties \
		--out-object=states \
		--key='d.id.substring(0, 2)' \
		-- $<

us.json: build/states.json
	node_modules/.bin/topojson-merge \
		-o $@ \
		--in-object=states \
		--out-object=nation \
		-- $<
```

Here is what I'm receiving

```
~/ $ make
mkdir -p build/
curl -o build/gz_2010_us_050_00_20m.zip http://www2.census.gov/geo/tiger/GENZ2010/gz_2010_us_050_00_20m.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1277k  100 1277k    0     0   646k      0  0:00:01  0:00:01 --:--:--  646k
unzip -od build/ build/gz_2010_us_050_00_20m.zip
Archive:  build/gz_2010_us_050_00_20m.zip
  inflating: build/gz_2010_us_050_00_20m.dbf  
  inflating: build/gz_2010_us_050_00_20m.prj  
  inflating: build/gz_2010_us_050_00_20m.shp  
  inflating: build/gz_2010_us_050_00_20m.shx  
  inflating: build/gz_2010_us_050_00_20m.xml  
touch build/gz_2010_us_050_00_20m.shp
node_modules/.bin/topojson \
		-o build/counties.json \
		--projection='width = 960, height = 600, d3.geo.albersUsa() \
			.scale(1280) \
			.translate([width / 2, height / 2])' \
		--simplify=.5 \
		-- counties=build/gz_2010_us_050_00_20m.shp
module.js:338
    throw err;
          ^
Error: Cannot find module 'rw'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/bensullins/Dropbox (Personal)/pluralsight/ben-sullins/d3js-mapping/m3-drawing-maps/county-bubble-map/node_modules/.bin/topojson:4:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
make: *** [build/counties.json] Error 1
```

**Comment by bsullins** [comment]
Apparently this was caused by an extra tab `>>` character :anguished:
