### ISSUE TITLE
Topojson appears to install, but won't run

### ISSUE THREAD

**Issue by slead** [mbostock/topojson#284]
Hi there,

I'm a node and npm novice, so apologies if these are obvious questions. I have node and npm installed on OSX El Capitan:

```
node -v -> v0.10.28
npm -v -> 3.10.6
```
so I install topojson using:

```
npm install -g topojson
/usr/local/bin/topojson-geojson -> /usr/local/lib/node_modules/topojson/bin/topojson-geojson
/usr/local/bin/topojson -> /usr/local/lib/node_modules/topojson/bin/topojson
/usr/local/bin/topojson-group -> /usr/local/lib/node_modules/topojson/bin/topojson-group
/usr/local/bin/topojson-merge -> /usr/local/lib/node_modules/topojson/bin/topojson-merge
/usr/local/bin/topojson-svg -> /usr/local/lib/node_modules/topojson/bin/topojson-svg
/usr/local/lib
└── topojson@1.6.26 
```

I can confirm these files were installed:

```
ls -l /usr/local/bin/topo*
lrwxr-xr-x  1 steve  admin    41B  5 Sep 13:54 /usr/local/bin/topojson@ -> ../lib/node_modules/topojson/bin/topojson
lrwxr-xr-x  1 steve  admin    49B  5 Sep 13:54 /usr/local/bin/topojson-geojson@ -> ../lib/node_modules/topojson/bin/topojson-geojson
lrwxr-xr-x  1 steve  admin    47B  5 Sep 13:54 /usr/local/bin/topojson-group@ -> ../lib/node_modules/topojson/bin/topojson-group
lrwxr-xr-x  1 steve  admin    47B  5 Sep 13:54 /usr/local/bin/topojson-merge@ -> ../lib/node_modules/topojson/bin/topojson-merge
lrwxr-xr-x  1 steve  admin    45B  5 Sep 13:54 /usr/local/bin/topojson-svg@ -> ../lib/node_modules/topojson/bin/topojson-svg

```
But I can't run any topojson commands, including `topojson -v`.  There is no response from the terminal, just a frozen prompt which I need to CTRL-C out of.

Thanks for any advice.

**Comment by mbostock** [comment]
There is no -v option to the topojson command line tool, so running `topojson -v` is equivalent to running `topojson` with no arguments, and in that case the input file defaults to stdin. So, if you have a frozen prompt, it’s because the topojson command is waiting for the end of the input file. If you hit ^D (ctrl-D) to end the input you should see something like this:

```
/usr/local/lib/node_modules/topojson/bin/topojson:259
  if (error) throw error;
             ^

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at inputJson (/usr/local/lib/node_modules/topojson/bin/topojson:245:21)
    at start (/usr/local/lib/node_modules/topojson/node_modules/d3-queue/build/d3-queue.js:68:13)
    at poke (/usr/local/lib/node_modules/topojson/node_modules/d3-queue/build/d3-queue.js:56:26)
    at Queue.queue.defer (/usr/local/lib/node_modules/topojson/node_modules/d3-queue/build/d3-queue.js:34:7)
    at /usr/local/lib/node_modules/topojson/bin/topojson:196:5
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/topojson/bin/topojson:195:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

If you want to test your topojson install, try `topojson --help`:

```
Usage: topojson [options] -- [file …]

Version: 1.6.27

Converts the specified input shapefile, GeoJSON or TopoJSON objects to
TopoJSON, outputting a single TopoJSON topology object. The `objects`
property of the output topology is a map from input file name to geometry
object.

Options:
  -o, --out                      output TopoJSON file name                                                    [default: "-"]
  -q, --quantization             convenience option for setting pre- and post-quantization                  
  --q0, --pre-quantization       maximum number of differentiable points along either dimension               [default: 1000000]
  --q1, --post-quantization      maximum number of differentiable points along either dimension               [default: 10000]
  -s, --simplify                 area threshold for simplification (steradians for spherical coordinates)     [default: 0]
  --simplify-proportion          proportion of points to retain for simplification                            [default: 0]
  --cartesian                    assume Cartesian input coordinates                                           [boolean]  [default: false]
  --spherical                    assume spherical input coordinates                                           [boolean]  [default: false]
  --force-clockwise              force clockwise exterior rings and counterclockwise interior rings           [boolean]  [default: true]
  --stitch-poles                 splice antimeridian cuts for polygons that encompass a pole                  [boolean]  [default: true]
  --filter                       which rings to remove after simplifying; one of {none,small,small-detached}  [string]  [default: "small-detached"]
  --allow-empty                  deprecated; use --filter=none instead                                        [boolean]  [default: false]
  --id-property                  name of feature property to promote to geometry id                           [default: null]
  -p, --properties               feature properties to preserve; no name preserves all properties             [default: false]
  -e, --external-properties      CSV or TSV file to join properties (by id) to output features              
  --shapefile-encoding           character encoding for reading shapefile properties                          [default: null]
  --ignore-shapefile-properties  skip reading shapefile properties (.dbf) for faster performance              [boolean]  [default: false]
  -x, --longitude                name of the x (longitude) property for CSV or TSV geometry input             [default: "longitude"]
  -y, --latitude                 name of the y (latitude) property for CSV or TSV geometry input              [default: "latitude"]
  --projection                   name of a projection to apply (implies spherical input)                      [default: null]
  --width                        scale and translate to fit a viewport of the specified width                 [default: null]
  --height                       scale and translate to fit a viewport of the specified height                [default: null]
  --margin                       pixels of margin to reserve when scaling to fit a viewport                   [default: 0]
  --invert                       in conjunction with --width or --height, whether to invert y                 [boolean]  [default: "auto"]
  --bbox                         include bbox property in generated topology                                  [boolean]  [default: false]
  --help                         display this helpful message                                                 [boolean]  [default: false]
  --version                      print the version number and exit                                            [boolean]  [default: false]

```
